# -*- coding: utf-8 -*-
"""mergeData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxf2cFbt3A4rieA5bqT7pm9-Xlv3oeGA
"""

# import libraries
import pandas as pd
from google.colab import files

# load in the datasets
wordData1 = pd.read_csv("google-books-common-words.csv")
wordData2 = pd.read_csv("kaggle_freq.csv")
wordData3 = pd.read_csv("wordFrequency.csv")

# words in 1st dataset are all caps - change to lower case
wordData1["word"] = wordData1["word"].str.lower()

# create combined dataset by merging 3 smaller ones
combinedData = pd.merge(wordData1, wordData2, on="word", how="outer").fillna(0)
combinedData['frequency'] = combinedData['frequency_x'] + combinedData['frequency_y']
combinedData = combinedData[['word', 'frequency']]

# print(combinedData.head(10))

# used this to test if first two datasets merged properly
# combinedData.to_csv('combinedWordFrequencies.csv')
# from google.colab import files
# files.download('combinedWordFrequencies.csv')

# now merge with last one
combinedData = pd.merge(combinedData, wordData3, on="word", how="outer").fillna(0)
combinedData['frequency'] = combinedData['frequency_x'] + combinedData['frequency_y']
combinedData = combinedData[['word', 'frequency']]
combinedData = combinedData.groupby('word')

# print(combinedData.head(10))

# APPROACH 2
# combinedData = wordData3.merge(wordData1, on="word", how="left").merge(wordData2, on='word', how='left').fillna(0)
# combinedData['frequency'] = combinedData['frequency_x'] + combinedData['frequency_y'] + combinedData['frequency']
# combinedData = combinedData[['word', 'frequency']]
# print(combinedData.head(10))

# save combined to computer and sort it
combinedData.sum().sort_values('frequency', ascending=False).to_csv('combinedWordFrequencies.csv')
files.download('combinedWordFrequencies.csv')